export const modules = [
  {
    id: 'emergency-response',
    title: 'Emergency Response Protocol',
    description: 'Learn critical emergency response procedures in a safe VR environment',
    category: 'Safety',
    difficulty: 'Intermediate',
    duration: 15,
    image: 'https://images.unsplash.com/photo-1578975494453-3b5b17a04eaf?w=400&h=300&fit=crop',
    participants: 1234,
  },
  {
    id: 'surgical-training',
    title: 'Advanced Surgical Techniques',
    description: 'Master complex surgical procedures with realistic haptic feedback',
    category: 'Medical',
    difficulty: 'Advanced',
    duration: 45,
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=300&fit=crop',
    participants: 856,
  },
  {
    id: 'equipment-maintenance',
    title: 'Industrial Equipment Maintenance',
    description: 'Practice proper maintenance procedures on heavy machinery',
    category: 'Industrial',
    difficulty: 'Beginner',
    duration: 20,
    image: 'https://images.unsplash.com/photo-1581092165854-40860a2fb69b?w=400&h=300&fit=crop',
    participants: 2103,
  },
  {
    id: 'hazmat-handling',
    title: 'Hazardous Materials Handling',
    description: 'Safely handle and dispose of hazardous materials in realistic scenarios',
    category: 'Safety',
    difficulty: 'Advanced',
    duration: 30,
    image: 'https://images.unsplash.com/photo-1581092916550-eac41bedc3e0?w=400&h=300&fit=crop',
    participants: 567,
  },
  {
    id: 'customer-service',
    title: 'VR Customer Service Excellence',
    description: 'Develop interpersonal skills through immersive customer interactions',
    category: 'Business',
    difficulty: 'Beginner',
    duration: 25,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
    participants: 3421,
  },
  {
    id: 'drone-operation',
    title: 'Drone Piloting Certification',
    description: 'Complete comprehensive drone pilot training and certification',
    category: 'Technical',
    difficulty: 'Intermediate',
    duration: 35,
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=300&fit=crop',
    participants: 1876,
  },
]

export const leaderboard = [
  { rank: 1, username: 'VR_Champion', score: 9850, completedModules: 18, badge: '⭐' },
  { rank: 2, username: 'SimulatorMaster', score: 9620, completedModules: 17, badge: '🏆' },
  { rank: 3, username: 'TrainingPro', score: 9410, completedModules: 16, badge: '🥇' },
  { rank: 4, username: 'ImmersiveExp', score: 9180, completedModules: 15, badge: '🥈' },
  { rank: 5, username: 'ProcedureExp', score: 8950, completedModules: 14, badge: '🥉' },
  { rank: 6, username: 'TechTrainer', score: 8720, completedModules: 13, badge: '' },
  { rank: 7, username: 'SafetyFirst', score: 8490, completedModules: 12, badge: '' },
  { rank: 8, username: 'SkillBuilder', score: 8260, completedModules: 11, badge: '' },
]

export const userStats = {
  userId: 'user-123',
  username: 'UserProfile',
  totalScore: 7850,
  rank: 42,
  completedModules: 9,
  totalModules: 18,
  averageScore: 872,
  recentActivity: [
    { moduleId: 'emergency-response', moduleName: 'Emergency Response Protocol', score: 945, date: '2024-03-20' },
    { moduleId: 'surgical-training', moduleName: 'Advanced Surgical Techniques', score: 892, date: '2024-03-18' },
    { moduleId: 'equipment-maintenance', moduleName: 'Industrial Equipment Maintenance', score: 956, date: '2024-03-16' },
    { moduleId: 'customer-service', moduleName: 'VR Customer Service Excellence', score: 834, date: '2024-03-14' },
  ],
}
